#!/bin/bash

if [ ! -x /usr/bin/ascii-xfr ]; then
    echo "WARNING: To send ASCII files through picocom, please install ascii-xfr (included in package minicom)."
fi

echo "Use Ctrl-A Ctrl-S to send a text file."

picocom --baud 115200 --flow n --parity n --databits 8 \
        --send-cmd "ascii-xfr -s -nv" --imap lfcrlf \
        /dev/ttyUSB1
